# Choosing CRS
Compare richness maps using degree approximation and various reprojection options

# 
https://www.pmassicotte.com/posts/2021-11-12-choosing-the-right-projection/
```{r}
library(rnaturalearth)
library(sf)
library(patchwork)
#install.packages("crsuggest")
library(crsuggest)
```

```{r}
data_path_L0<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
# load in shapefile
TropicalAndes_IUCNHabitat_Forest <- read_sf(file.path(data_path_L0, "Forest_sf.shp"), layer = "Forest_sf")
```

```{r}
worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")
#polygon of Tropical Andes
TApoly <- worldMap %>% filter(sovereignt == "Bolivia" |sovereignt == "Ecuador" | sovereignt == "Venezuela" | sovereignt == "Colombia" | sovereignt == "Peru")
```

```{r}
st_crs(TApoly)$proj4string
```
```{r}
st_crs(TropicalAndes_IUCNHabitat_Forest)$proj4string
```
```{r}
p1 <- ggplot() +
  geom_sf(data = TApoly)

p1
```
```{r}
p2 <- ggplot() +
  geom_sf(data = TropicalAndes_IUCNHabitat_Forest)

p2
```

```{r}
suggested_crs_TA <- suggest_crs(TApoly, limit = 5)
suggested_crs_TA
```
```{r}
plot_map <- function(crs, map) {
  ggplot() +
    geom_sf(data = map) +
    coord_sf(crs = as.numeric(crs)) +
    labs(
      title = paste("CRS:", crs)
    )
}

maps <- lapply(suggested_crs_TA$crs_code, plot_map, map = TApoly)
wrap_plots(maps, ncol = 3, nrow = 2)
```
```{r}
p2 <- ggplot() +
  geom_sf(data = map) +
  coord_sf(crs = 5922)

p1 + p2
```


# One Option 
+proj=aea +lat_0=-32 +lon_0=-60 +lat_1=-5 +lat_2=-42 +x_0=0 +y_0=0 +ellps=aust_SA +units=m +no_defs +type=crs
