---
title: "Frugivoria frugivore trait subset"
author: "Hazel J. Anderson"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "Subsetting Frugivoria to the species and traits of interest."
data input: "TropicalAndes_Frugivoria_frugivore_traits.csv, TropicalAndes_GBIF_frugivore_occ_cleaned.csv"
data output: "TropicalAndes_Frugivoria_traits_subset.csv"
date: "2023-10-31"
output: 
  html_document:
    code-link: true
---

# Load required packages
```{r}
library(dplyr)
library(funbiogeo)
library(visdat)
```

# Set file paths
```{r}
data_path_L0<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
data_path_L1<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
```

# Read in data
```{r}
Frugivoria <- read.csv(file.path(data_path_L0, file = "TropicalAndes_Frugivoria_frugivore_traits.csv"))
frugivore_occ <- read.csv(file.path(data_path_L1, file = "TropicalAndes_GBIF_frugivore_occ_cleaned.csv"))
```

# Get species list from frugivore_occ data
```{r}
frugivore_species <- unique(frugivore_occ$species)
```

# Subset Frugivoria by species list
```{r}
Frugivoria_filtered <- Frugivoria %>%
  filter(IUCN_species_name %in% frugivore_species)
```

# Keep only traits of interest
```{r}
# keep columns with traits of diet category, body size, body mass, generation time
Frugivoria_subset <- Frugivoria_filtered[ , c("IUCN_species_name", "family", "genus", "species", "diet_cat", "body_mass_e", "body_size_mm", "generation_time")]
```

# Summary
```{r}
glimpse(Frugivoria_subset)
```

```{r}
source("~/GitHub/neotropical_plants/code/data_summary.R")
```

```{r}
data_summary(Frugivoria_subset, Frugivoria_subset$species, Frugivoria_subset$genus, Frugivoria_subset$family)
```

```{r}
fb_plot_species_traits_completeness(Frugivoria_subset)
fb_plot_number_species_by_trait(Frugivoria_subset)
fb_table_trait_summary(Frugivoria_subset)
```

```{r}
vis_dat(Frugivoria_subset)
vis_miss(Frugivoria_subset)
```

# Write data to csv
```{r}
write.csv(Frugivoria_subset, file.path(output_path,"TropicalAndes_Frugivoria_traits_subset.csv"))
```

# Package citations and session info
```{r}
library(report)
report::cite_packages()

devtools::session_info()
```