---
title: "Cleaning Tropical Andes plant GBIF occurrence records"
author: "Hazel J. Anderson and Jenna B. Baljunas"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "Uses CoordinateCleaner to flag and remove problematic records from GBIF plant occurrence records."
data input: "TropicalAndes_GBIF_plant_occ.csv"
data output: "TropicalAndes_GBIF_plant_occ_cleaned.csv, TropicalAndes_GBIF_plant_occ_flagged.csv"
date: "2023-07-25"
output: html_document
---

# Set file paths
```{r}
data_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
source("C:/GitHub_projects/plant-frugivore diversity/neotropical_plants/code/data_summary.R")
```

# Load required packages
```{r}
library(countrycode)
library(CoordinateCleaner)
library(dplyr)
```

# Read in data
```{r}
TropicalAndes_GBIF_plant_occ <- read.csv(file.path(data_path,"TropicalAndes_GBIF_plant_occ.csv"))
```

# Clean data
Adapted code from https://ropensci.github.io/CoordinateCleaner/articles/Cleaning_GBIF_data_with_CoordinateCleaner.html 

```{r}
# remove records without coordinates
TropicalAndes_GBIF_plant_occ <- TropicalAndes_GBIF_plant_occ %>%
  filter(!is.na(decimalLongitude)) %>%
  filter(!is.na(decimalLatitude))
```

```{r}
# had to split this up
flags <- clean_coordinates(x = TropicalAndes_GBIF_plant_occ[1:2000000,],
                           lon= "decimalLongitude",
                           lat = "decimalLatitude",
                           countries = "countryCode",
                           species = "species",
                           tests = c("capitals", "centroids",
                                     "duplicates", "equal", "gbif",
                                     "institutions", "seas","zeros"))

flags2 <- clean_coordinates(x = TropicalAndes_GBIF_plant_occ[2000001:4017912,],
                           lon= "decimalLongitude",
                           lat = "decimalLatitude",
                           countries = "countryCode",
                           species = "species",
                           tests = c("capitals", "centroids",
                                     "duplicates", "equal", "gbif",
                                     "institutions", "seas","zeros"))
summary(flags)
summary(flags2)
```

```{r}
#exclude problematic records
TropicalAndes_GBIF_plant_occ1 <- TropicalAndes_GBIF_plant_occ[1:2000000,]
TropicalAndes_GBIF_plant_occ_cleaned1 <- TropicalAndes_GBIF_plant_occ1[flags$.summary,]
TropicalAndes_GBIF_plant_occ_flagged1 <- TropicalAndes_GBIF_plant_occ1[!flags$.summary,]

TropicalAndes_GBIF_plant_occ2 <- TropicalAndes_GBIF_plant_occ[2000001:4017912,]
TropicalAndes_GBIF_plant_occ_cleaned2 <- TropicalAndes_GBIF_plant_occ2[flags2$.summary,]
TropicalAndes_GBIF_plant_occ_flagged2 <- TropicalAndes_GBIF_plant_occ2[!flags2$.summary,]

rm(TropicalAndes_GBIF_plant_occ,flags,flags2)
```

```{r}
# merge
TropicalAndes_GBIF_plant_occ_cleaned <- rbind(TropicalAndes_GBIF_plant_occ_cleaned1,TropicalAndes_GBIF_plant_occ_cleaned2)

rm(TropicalAndes_GBIF_plant_occ_cleaned1,TropicalAndes_GBIF_plant_occ_cleaned2)
```

# Summary
```{r}
glimpse(TropicalAndes_GBIF_plant_occ_cleaned)
```

```{r}
data_summary(TropicalAndes_GBIF_plant_occ_cleaned, TropicalAndes_GBIF_plant_occ_cleaned$species, TropicalAndes_GBIF_plant_occ_cleaned$genus, TropicalAndes_GBIF_plant_occ_cleaned$family)
```

# Write data to csv
```{r}
flags3 <- clean_coordinates(x = TropicalAndes_GBIF_plant_occ_cleaned,
                           lon= "decimalLongitude",
                           lat = "decimalLatitude",
                           countries = "countryCode",
                           species = "species",
                           tests = c("capitals", "centroids",
                                     "duplicates", "equal", "gbif",
                                     "institutions", "seas","zeros"))

TropicalAndes_GBIF_plant_occ_cleaned2 <- TropicalAndes_GBIF_plant_occ_cleaned[flags3$.summary,]

write.csv(TropicalAndes_GBIF_plant_occ_cleaned2, file = file.path(output_path,"TropicalAndes_GBIF_plant_occ_cleaned.csv"))

rm(TropicalAndes_GBIF_plant_occ_cleaned)
```

```{r}
TropicalAndes_GBIF_plant_occ_flagged3 <- TropicalAndes_GBIF_plant_occ_cleaned2[!flags3$.summary,]

TropicalAndes_GBIF_plant_occ_flagged <- rbind(TropicalAndes_GBIF_plant_occ_flagged1,TropicalAndes_GBIF_plant_occ_flagged2,TropicalAndes_GBIF_plant_occ_flagged3)

rm(TropicalAndes_GBIF_plant_occ_flagged1,TropicalAndes_GBIF_plant_occ_flagged2)

write.csv(TropicalAndes_GBIF_plant_occ_flagged, file = file.path(output_path,"TropicalAndes_GBIF_plant_occ_flagged.csv"))
```