
Get synonmyms for species list 

# Set file paths
```{r}
data_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
data_path2 <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
output_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
```

```{r}
library(taxadb)
```

```{r}
#create local itis database
td_create("itis",overwrite=FALSE)
```

# Read in species lists
```{r}
TRY_species <- read.csv(file.path(data_path,"TropicalAndes_TRY_plant_species.csv"))
BIEN_species <- read.csv(file.path(data_path,"TropicalAndes_BIEN_plant_trait_species.csv"))
GBIF_species <- read.csv(file.path(data_path2,"TropicalAndes_plant_Forest_SpeciesList.csv"))
```

# Combine species lists
```{r}
allnames <- rbind(TRY_species, BIEN_species, GBIF_species)
```


```{r}
#get  IDS for each scientific name
syn1<-allnames %>%
  select(Scientific.Name) %>%
  mutate(ID=get_ids(Scientific.Name,"itis"))

#Deal with NAs (one name corresponds to more than 1 ITIS code) (~10k names)

syn1_NA<-as.data.frame(syn1$Scientific.Name[is.na(syn1$ID)])
colnames(syn1_NA)<-c("name")

NA_IDS<-NULL
for(i in unique(syn1_NA$name)){
  tmp<-as.data.frame(filter_name(i, 'itis')[5])
  tmp$name<-paste0(i)
  NA_IDS<-rbind(NA_IDS,tmp)
}

#join with original names
colnames(syn1)<-c("name","ID")
IDS<-left_join(syn1,NA_IDS,by="name") #I think its a left join double check this

#extract just the unique IDs
IDS<-data.frame(ID=c(IDS[,"ID"],IDS[,"acceptedNameUsageID"]))
IDS<-as.data.frame(unique(IDS$ID))
IDS<-as.data.frame(IDS[-is.na(IDS)])
colnames(IDS)<-"ID"
#extract all names with synonyms in ITIS that are at the species level [literally all of them]
#set query
ITIS<-taxa_tbl("itis") %>%
  select(scientificName,taxonRank,acceptedNameUsageID,taxonomicStatus) %>%
  filter(taxonRank == "species")

#see query
ITIS %>% show_query()
#retrieve results
ITIS_names<-ITIS %>% collect()

#filter to only those that match ITIS codes for all my species
ITIS_names<-ITIS_names %>%
  filter(acceptedNameUsageID %in% IDS$ID)
```

