Func Div troubleshooting

```{r}
# getting sp_faxes_coord_plants and subset_matrix_plants names to match
sp_faxes_coord_plants_sub <- sp_faxes_coord_plants[ , c("PC1", "PC2", "PC3", "PC4")]
## check number of species names
nrow(sp_faxes_coord_plants_sub) # 54
ncol(subset_matrix_plant) #82

sp_faxes_coord_plants_sub_names <- row.names(sp_faxes_coord_plants_sub)
subset_matrix_plant_names <- colnames(subset_matrix_plant)

sp_faxes_coord_plants_sub_df <- as.data.frame(sp_faxes_coord_plants_sub)
subset_matrix_plant_df <- as.data.frame(subset_matrix_plant)

subset_matrix_plant <- subset_matrix_plant_df[, which((names(subset_matrix_plant_df) %in% sp_faxes_coord_plants_sub_names)==TRUE)]

ncol(subset_matrix_plant)
subset_matrix_plant <- as.matrix(subset_matrix_plant)
```

```{r}
#computing FD
# The number of species per assemblage has to be higher or equal to the number of traits
alpha_fd_indices_plant <- mFD::alpha.fd.multidim(
  sp_faxes_coord   = sp_faxes_coord_plants,
  asb_sp_w         = PAM_plant_site_final,
  ind_vect         = c("fide", "fdis", "fmpd", "fnnd", "feve", "fori", "fspe"), #did not run fdiv or fric (slows it down)
  scaling          = TRUE,
  check_input      = TRUE,
  details_returned = TRUE)

alpha_fd_indices_frugivore <- mFD::alpha.fd.multidim(
  sp_faxes_coord   = sp_faxes_coord_frugivore,
  asb_sp_w         = PAM_plant_site_final,
  ind_vect         = c("fide", "fdis", "fmpd", "fnnd", "feve", "fori", "fspe"), #did not run fdiv or fric (slows it down)
  scaling          = TRUE,
  check_input      = TRUE,
  details_returned = TRUE)

details_list_plant <- alpha_fd_indices_plant$"details"
details_list_frugivore <- alpha_fd_indices_frugivore$"details"

#plot
plots_alpha_plant <- mFD::alpha.multidim.plot(
  output_alpha_fd_multidim = alpha_fd_indices_plant,
  plot_asb_nm              = c("cell4", "cell20"),
  ind_nm                   = c("fdis", "fide", "fnnd"
                        , "fori", "fspe"),
  faxes                    = NULL,
  faxes_nm                 = NULL,
  range_faxes              = c(NA, NA),
  color_bg                 = "grey95",
  shape_sp                 = c(pool = 3, asb1 = 21, asb2 = 21),
  size_sp                  = c(pool = 0.7, asb1 = 1, asb2 = 1),
  color_sp                 = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  color_vert               = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  fill_sp                  = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  fill_vert                = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  color_ch          
  = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  fill_ch                  = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  alpha_ch                 = c(pool = 1, asb1 = 0.3, asb2 = 0.3),
  shape_centroid_fdis      = c(asb1 = 22,  asb2 = 24),
  shape_centroid_fdiv      = c(asb1 = 22,  asb2 = 24),
  shape_centroid_fspe      = 23,
  color_centroid_fspe      = "black",
  size_sp_nm               = 3, 
  color_sp_nm              = "black",
  plot_sp_nm               = NULL,
  fontface_sp_nm           = "plain",
  save_file                = FALSE,
  check_input              = TRUE)

plots_alpha_frugivore <- mFD::alpha.multidim.plot(
  output_alpha_fd_multidim = alpha_fd_indices_frugivore,
  plot_asb_nm              = c("cell4", "cell20"),
  ind_nm                   = c("fdis", "fide", "fnnd"
                        , "fori", "fspe"),
  faxes                    = NULL,
  faxes_nm                 = NULL,
  range_faxes              = c(NA, NA),
  color_bg                 = "grey95",
  shape_sp                 = c(pool = 3, asb1 = 21, asb2 = 21),
  size_sp                  = c(pool = 0.7, asb1 = 1, asb2 = 1),
  color_sp                 = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  color_vert               = c(pool = "grey50", asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  fill_sp                  = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  fill_vert                = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  color_ch          
  = c(pool = NA, asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  fill_ch                  = c(pool = "white", asb1 = "#1F968BFF", asb2 = "#DCE319FF"),
  alpha_ch                 = c(pool = 1, asb1 = 0.3, asb2 = 0.3),
  shape_centroid_fdis      = c(asb1 = 22,  asb2 = 24),
  shape_centroid_fdiv      = c(asb1 = 22,  asb2 = 24),
  shape_centroid_fspe      = 23,
  color_centroid_fspe      = "black",
  size_sp_nm               = 3, 
  color_sp_nm              = "black",
  plot_sp_nm               = NULL,
  fontface_sp_nm           = "plain",
  save_file                = FALSE,
  check_input              = TRUE) 

plots_alpha_plant$"fric"$"patchwork"  #comparing convex hulls of different hulls
plots_alpha_frugivore$"fric"$"patchwork"
plots_alpha_plant$"fdiv"$"patchwork"
plots_alpha_frugivore$"fdiv"$"patchwork"
plots_alpha_plant$"fspe"$"patchwork"
plots_alpha_frugivore$"fspe"$"patchwork"
plots_alpha_plant$"fdis"$"patchwork"
plots_alpha_frugivore$"fdis"$"patchwork"
plots_alpha_plant$"fori"$"patchwork"
plots_alpha_frugivore$"fori"$"patchwork"
```