---
title: "Tropical Andes Functional diversity for plants and Frugivores"
author: "Hazel J. Anderson"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "This script calculates functional diversity as functional dispersion for plants and frugivores."
date: "2023-08-03"
output: html_document
---

# Load required packages
```{r}
library(mFD)
library(sf)
library(dplyr)
library(ggplot2)
library(rnaturalearth)
library(ggspatial)
library(rlang)
library(doParallel)
library(foreach)
```

# Set file paths
```{r}
data_path_L1 <-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
output_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L2')
figure_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/figures')
```

# Read in Data

```{r}
## projected sf objects
plants_sf_species <- readRDS(file = file.path(data_path_L1,"plants_sf_species.rds"))
frugivores_sf_species <- readRDS(file = file.path(data_path_L1,"frugivores_sf_species.rds"))
Americas <- readRDS(file = file.path(data_path_L1, "Americas.rds"))
TApoly <- readRDS(file = file.path(data_path_L1,"TApoly.rds"))
TropicalAndes_IUCNHabitat_Forest <- readRDS(file = file.path(data_path_L1,"TropicalAndes_IUCNHabitat_Forest.rds"))
```

```{r}
plant_traits_df_final <- readRDS(file = file.path(data_path_L1,"plant_traits_df_final.rds"))
frugivore_traits_df_final <- readRDS(file = file.path(data_path_L1,"frugivore_traits_df_final.rds"))
```

```{r}
site_loc_key_plant_100km <- readRDS(file = file.path(data_path_L1,"site_loc_key_plant_100km.rds"))
site_loc_key_frugivore_100km <- readRDS(file = file.path(data_path_L1,"site_loc_key_frugivore_100km.rds"))
PAM_plant_site_final_100km <- readRDS(file = file.path(data_path_L1,"PAM_plant_site_final_100km.rds"))
PAM_frugivore_site_final_100km <- readRDS(file = file.path(data_path_L1,"PAM_frugivore_site_final_100km.rds"))
```

```{r}
site_loc_key_plant_75km <- readRDS(file = file.path(data_path_L1,"site_loc_key_plant_75km.rds"))
site_loc_key_frugivore_75km <- readRDS(file = file.path(data_path_L1,"site_loc_key_frugivore_75km.rds"))
PAM_plant_site_final_75km <- readRDS(file = file.path(data_path_L1,"PAM_plant_site_final_75km.rds"))
PAM_frugivore_site_final_75km <- readRDS(file = file.path(data_path_L1,"PAM_frugivore_site_final_75km.rds"))
```

```{r}
site_loc_key_plant_50km <- readRDS(file = file.path(data_path_L1,"site_loc_key_plant_50km.rds"))
site_loc_key_frugivore_50km <- readRDS(file = file.path(data_path_L1,"site_loc_key_frugivore_50km.rds"))
PAM_plant_site_final_50km <- readRDS(file = file.path(data_path_L1,"PAM_plant_site_final_50km.rds"))
PAM_frugivore_site_final_50km <- readRDS(file = file.path(data_path_L1,"PAM_frugivore_site_final_50km.rds"))
```

```{r}
site_loc_key_plant_25km <- readRDS(file = file.path(data_path_L1,"site_loc_key_plant_25km.rds"))
site_loc_key_frugivore_25km <- readRDS(file = file.path(data_path_L1,"site_loc_key_frugivore_25km.rds"))
PAM_plant_site_final_25km <- readRDS(file = file.path(data_path_L1,"PAM_plant_site_final_25km.rds"))
PAM_frugivore_site_final_25km <- readRDS(file = file.path(data_path_L1,"PAM_frugivore_site_final_25km.rds"))
```

```{r}
site_loc_key_plant_10km <- readRDS(file = file.path(data_path_L1,"site_loc_key_plant_10km.rds"))
site_loc_key_frugivore_10km <- readRDS(file = file.path(data_path_L1,"site_loc_key_frugivore_10km.rds"))
PAM_plant_site_final_10km <- readRDS(file = file.path(data_path_L1,"PAM_plant_site_final_10km.rds"))
PAM_frugivore_site_final_10km <- readRDS(file = file.path(data_path_L1,"PAM_frugivore_site_final_10km.rds"))
```

```{r}
site_loc_key_plant_5km <- readRDS(file = file.path(data_path_L1,"site_loc_key_plant_5km.rds"))
site_loc_key_frugivore_5km <- readRDS(file = file.path(data_path_L1,"site_loc_key_frugivore_5km.rds"))
PAM_plant_site_final_5km <- readRDS(file = file.path(data_path_L1,"PAM_plant_site_final_5km.rds"))
PAM_frugivore_site_final_5km <- readRDS(file = file.path(data_path_L1,"PAM_frugivore_site_final_5km.rds"))
```

# Create trait type tables
```{r}
trait_name <- c("diet_cat", "body_mass_e", "body_size_mm", "generation_time")
trait_type <- c("N", "Q", "Q", "Q")
frug_trait_cat <- as.data.frame(cbind(trait_name, trait_type))
```

```{r}
trait_name <- c("PlantLifespan_years","GrowthForm", "SeedMass_g", "PlantHeight_m", "FruitType", "FruitLength_mm",
                "SeedWidth_mm", "FruitMass_mg", "SeedLength_mm", "DispersalSyndrome")
trait_type <- c("Q", "N", "Q", "Q", "N", "Q", "Q", "Q", "Q", "N") 
plant_trait_cat <- as.data.frame(cbind(trait_name, trait_type))
```

```{r}
# fix Nominal traits as factor
frugivore_traits_df_final$diet_cat <- as.factor(frugivore_traits_df_final$diet_cat)

plant_traits_df_final$GrowthForm <- as.factor(plant_traits_df_final$GrowthForm)
plant_traits_df_final$FruitType <- as.factor(plant_traits_df_final$FruitType)
plant_traits_df_final$DispersalSyndrome <- as.factor(plant_traits_df_final$DispersalSyndrome)
```

# Create function
```{r}

```


# Frugivores
## 100 km
```{r}
# Summary of the assemblages * species dataframe
asb_sp_frugivore_summ <- mFD::asb.sp.summary(asb_sp_w = PAM_frugivore_site_final_100km)
```

```{r}
# Species traits summary
frugivore_traits_summ <- mFD::sp.tr.summary(tr_cat = frug_trait_cat, sp_tr = frugivore_traits_df_final)
```

```{r}
# Estimate functional trait-based distances between species
sp_dist_frugivore <- mFD::funct.dist( sp_tr = frugivore_traits_df_final, tr_cat = frug_trait_cat, metric = "gower",
  scale_euclid = "scale_center", ordinal_var = "classic", weight_type = "equal", stop_if_NA = TRUE)
```

```{r}
# Generate a multidimensional space
fspaces_quality_frugivore <- mFD::quality.fspaces(sp_dist = sp_dist_frugivore, maxdim_pcoa = 10, deviation_weighting = "absolute",
                                                  fdist_scaling = FALSE, fdendro = "average")
```

```{r}
# Look at the quality spaces only (MAD index looks at the mean absolute deviation from the dissimilarity matrix; want the deviation to be low meaning that the true distances have been retained in the PCA)
round(fspaces_quality_frugivore$"quality_fspaces", 3)
```

```{r}
# Plot the quality spaces (chose to look at 3D, 4D, and 5D since they had the lowest MAD). Will go with 3 dimensions
mFD::quality.fspaces.plot(fspaces_quality = fspaces_quality_frugivore, quality_metric = "mad",
                          fspaces_plot = c("pcoa_3d", "pcoa_4d", "pcoa_5d"))
```

```{r}
#testing correlation between functional axes and traits
sp_faxes_coord_frugivore <- fspaces_quality_frugivore$"details_fspaces"$"sp_pc_coord"
```

```{r}
# Computes linear model for continuous traits and Kruskall-Wallis tests for other types. 
frugivore_tr_faxes <- mFD::traits.faxes.cor(sp_tr = frugivore_traits_df_final, 
                                            sp_faxes_coord = sp_faxes_coord_frugivore[ , c("PC1", "PC2", "PC3", "PC4")],
                                            plot = TRUE)

# Print traits with significant effect:
frugivore_tr_faxes$"tr_faxes_stat"[which(frugivore_tr_faxes$"tr_faxes_stat"$"p.value" < 0.05), ]
# Return plots:
frugivore_tr_faxes$"tr_faxes_plot"
```

```{r}
#plotting functional space
sp_faxes_coord_frugivore <- fspaces_quality_frugivore$"details_fspaces"$"sp_pc_coord"

big_plot_frugivore <- mFD::funct.space.plot(sp_faxes_coord = sp_faxes_coord_frugivore[ , c("PC1", "PC2", "PC3", "PC4")],
                                            faxes = c("PC1", "PC2", "PC3", "PC4"), alpha_ch = 0.5, shape_vert = 6)
big_plot_frugivore
```

```{r}
#Need to remove parts of the PAM that have values less than or equal to the number of dimensions (3)
# Calculate row sums
row_sums_frugivore <- rowSums(PAM_frugivore_site_final_100km)
subset_matrix_frugivore <- PAM_frugivore_site_final_100km[row_sums_frugivore >= 3, ]
```

```{r}
# match frugivore names
sp_faxes_coord_frugivore_sub <- sp_faxes_coord_frugivore[ , c("PC1", "PC2", "PC3", "PC4")]
summary(sp_faxes_coord_frugivore_sub)
```


```{r}
## check number of species names
nrow(sp_faxes_coord_frugivore_sub)
ncol(subset_matrix_frugivore) 
```

```{r}
sp_faxes_coord_frugivore_sub_names <- row.names(sp_faxes_coord_frugivore_sub)
subset_matrix_frugivore_names <- colnames(subset_matrix_frugivore)
```

```{r}
sp_faxes_coord_frugivore_sub <- as.data.frame(sp_faxes_coord_frugivore_sub)
row.names(sp_faxes_coord_frugivore_sub) <- sp_faxes_coord_frugivore_sub_names

sp_faxes_coord_frugivore_sub_names <- row.names(sp_faxes_coord_frugivore_sub)
subset_matrix_frugivore_names <- colnames(subset_matrix_frugivore)

frugivore_names <- intersect(sp_faxes_coord_frugivore_sub_names, subset_matrix_frugivore_names)
frugivore_names <- na.omit(frugivore_names)

sp_faxes_coord_frugivore_sub <- sp_faxes_coord_frugivore_sub[ which((row.names(sp_faxes_coord_frugivore_sub) %in% frugivore_names)==TRUE), ]

subset_matrix_frugivore  <- as.data.frame(subset_matrix_frugivore)
subset_matrix_frugivore <- subset_matrix_frugivore[ ,which((colnames(subset_matrix_frugivore) %in% frugivore_names)==TRUE)]

#remove NAs
sp_faxes_coord_frugivore_sub <- na.omit(sp_faxes_coord_frugivore_sub)
subset_matrix_frugivore <- na.omit(subset_matrix_frugivore)
```

```{r}
nrow(sp_faxes_coord_frugivore_sub)
ncol(subset_matrix_frugivore)
```

```{r}
sp_faxes_coord_frugivore_sub <- as.matrix(sp_faxes_coord_frugivore_sub)
subset_matrix_frugivore <- as.matrix(subset_matrix_frugivore)
```

```{r}
# Computing FD
# The number of species per assemblage has to be higher or equal to the number of traits

alpha_fd_indices_frugivore <- mFD::alpha.fd.multidim(sp_faxes_coord = sp_faxes_coord_frugivore_sub, asb_sp_w = subset_matrix_frugivore,
                                                     ind_vect = "fdis", details_returned = TRUE)

details_list_frugivore <- alpha_fd_indices_frugivore$"details"
```

```{r}
# Get functional dispersion
fdis_frugivore <- alpha_fd_indices_frugivore$functional_diversity_indices$fdis
```


### Mapping FD

```{r}
# Generate coordinates
subset_coords_frugivore <-site_loc_key_frugivore_100km[rowSums(PAM_frugivore_site_final_100km) >= 3, ]
subset_coords_frugivore_sp <-subset_coords_frugivore[,1:2 ]

frugivore_fd_sp <- data.frame(subset_coords_frugivore_sp, fdis_frugivore)
```

```{r}
# Convert the dataframe to sf format
spatial_fdis_frugivore <- st_as_sf(frugivore_fd_sp, coords = c("Longitude", "Latitude"))
```

```{r}
# set crs of sf objects
spatial_fdis_frugivore <- spatial_fdis_frugivore %>% st_set_crs(5389)
```

```{r}
# Extract coordinates 
spatial_fdis_frugivore_coords <- st_coordinates(spatial_fdis_frugivore)

# Add coordinates as separate columns
spatial_fdis_frugivore <- spatial_fdis_frugivore %>%
  mutate(x = spatial_fdis_frugivore_coords[, 1], y = spatial_fdis_frugivore_coords[, 2])
```

```{r}
summary(spatial_fdis_frugivore)
```

```{r}
TAGrid_100km <- TApoly %>%
  st_make_grid(cellsize = c(100000)) %>%
  st_intersection(TropicalAndes_IUCNHabitat_Forest) %>%
  st_cast("MULTIPOLYGON") %>%
  st_sf() %>%
  mutate(cellid = row_number())

spatial_fdis_frugivore$cellid <- st_intersects(spatial_fdis_frugivore, TAGrid_100km)$nn

spatial_fdis_frugivore_grid <- TAGrid_100km %>%
   st_join(spatial_fdis_frugivore) %>%
   group_by(cellid) %>%
   summarize(fdis_value = sum(fdis_frugivore, na.rm = TRUE)) %>%
   ungroup()
```


```{r}
summary(spatial_fdis_frugivore_grid)
```

```{r}
frugivoregridFDisTA_100km <-
    ggplot() +
    geom_sf(data = Americas, fill = "white")+
    geom_sf(data = TApoly, fill = "lightgrey", size = 0.1) +
    geom_sf(data = spatial_fdis_frugivore_grid, aes(fill = fdis_value), color = NA) +
    labs(fill = "FDis") +
    ggtitle("100 km") +
    scale_fill_distiller(palette = "YlOrBr", direction = 1) +
    coord_sf(xlim = c(-82, -60), ylim = c(-24, 14), expand = FALSE, crs = 4326) +
    theme(panel.background = element_rect(fill = "lightblue"),
        text = element_text(size = 12), plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1))
frugivoregridFDisTA_100km
```

```{r}
# Extract cell values
frugivore_cellFDis_100km <- spatial_fdis_frugivore_grid
hist(frugivore_cellFDis_100km$fdis_value)
```

# Plants

## 100 km
```{r}
# Summary of the assemblages * species dataframe
asb_sp_plant_summ <- mFD::asb.sp.summary(asb_sp_w = PAM_plant_site_final_100km)
```

```{r}
# Species traits summary
plant_traits_summ <- mFD::sp.tr.summary(tr_cat = plant_trait_cat, sp_tr = plant_traits_df_final)
```

```{r}
# Estimate functional trait-based distances between species
sp_dist_plant <- mFD::funct.dist( sp_tr = plant_traits_df_final, tr_cat = plant_trait_cat, metric = "gower",
  scale_euclid = "scale_center", ordinal_var = "classic", weight_type = "equal", stop_if_NA = TRUE)
```

```{r}
# Generate a multidimensional space
fspaces_quality_plant <- mFD::quality.fspaces(sp_dist = sp_dist_plant, maxdim_pcoa = 10, deviation_weighting = "absolute",
                                                  fdist_scaling = FALSE, fdendro = "average")
```

```{r}
# Look at the quality spaces only (MAD index looks at the mean absolute deviation from the dissimilarity matrix; want the deviation to be low meaning that the true distances have been retained in the PCA)
round(fspaces_quality_plant$"quality_fspaces", 3)
```

```{r}
# Plot the quality spaces (chose to look at )
mFD::quality.fspaces.plot(fspaces_quality = fspaces_quality_plant, quality_metric = "mad",
                          fspaces_plot = c("pcoa_6d", "pcoa_7d", "pcoa_8d"))
```

```{r}
#testing correlation between functional axes and traits
sp_faxes_coord_plant <- fspaces_quality_plant$"details_fspaces"$"sp_pc_coord"
```

```{r}
# Computes linear model for continuous traits and Kruskall-Wallis tests for other types. 
plant_tr_faxes <- mFD::traits.faxes.cor(sp_tr = plant_traits_df_final, 
                                            sp_faxes_coord = sp_faxes_coord_plant[ , c("PC1", "PC2", "PC3", "PC4")],
                                            plot = TRUE)

# Print traits with significant effect:
plant_tr_faxes$"tr_faxes_stat"[which(plant_tr_faxes$"tr_faxes_stat"$"p.value" < 0.05), ]
# Return plots:
plant_tr_faxes$"tr_faxes_plot"
```

```{r}
#plotting functional space
sp_faxes_coord_plant <- fspaces_quality_plant$"details_fspaces"$"sp_pc_coord"

big_plot_plant <- mFD::funct.space.plot(sp_faxes_coord = sp_faxes_coord_plant[ , c("PC1", "PC2", "PC3", "PC4")],
                                            faxes = c("PC1", "PC2", "PC3", "PC4"), alpha_ch = 0.5, shape_vert = 6)
big_plot_plant
```

```{r}
#Need to remove parts of the PAM that have values less than or equal to the number of dimensions (4)
# Calculate row sums
row_sums_plant <- rowSums(PAM_plant_site_final_100km)
subset_matrix_plant <- PAM_plant_site_final_100km[row_sums_plant >= 4, ]
```

```{r}
# match plant names
sp_faxes_coord_plant_sub <- sp_faxes_coord_plant[ , c("PC1", "PC2", "PC3", "PC4")]
summary(sp_faxes_coord_plant_sub)
```

```{r}
## check number of species names
nrow(sp_faxes_coord_plant_sub)
ncol(subset_matrix_plant) 
```

```{r}
sp_faxes_coord_plant_sub_names <- row.names(sp_faxes_coord_plant_sub)
subset_matrix_plant_names <- colnames(subset_matrix_plant)
```

```{r}
sp_faxes_coord_plant_sub <- as.data.frame(sp_faxes_coord_plant_sub)
row.names(sp_faxes_coord_plant_sub) <- sp_faxes_coord_plant_sub_names

sp_faxes_coord_plant_sub_names <- row.names(sp_faxes_coord_plant_sub)
subset_matrix_plant_names <- colnames(subset_matrix_plant)

plant_names <- intersect(sp_faxes_coord_plant_sub_names, subset_matrix_plant_names)
plant_names <- na.omit(plant_names)

sp_faxes_coord_plant_sub <- sp_faxes_coord_plant_sub[ which((row.names(sp_faxes_coord_plant_sub) %in% plant_names)==TRUE), ]

subset_matrix_plant  <- as.data.frame(subset_matrix_plant)
subset_matrix_plant <- subset_matrix_plant[ ,which((colnames(subset_matrix_plant) %in% plant_names)==TRUE)]

#remove NAs
sp_faxes_coord_plant_sub <- na.omit(sp_faxes_coord_plant_sub)
subset_matrix_plant <- na.omit(subset_matrix_plant)
```

```{r}
nrow(sp_faxes_coord_plant_sub)
ncol(subset_matrix_plant)
```

```{r}
sp_faxes_coord_plant_sub <- as.matrix(sp_faxes_coord_plant_sub)
subset_matrix_plant <- as.matrix(subset_matrix_plant)
```

```{r}
# Computing FD
# The number of species per assemblage has to be higher or equal to the number of traits

alpha_fd_indices_plant <- mFD::alpha.fd.multidim(sp_faxes_coord = sp_faxes_coord_plant_sub, asb_sp_w = subset_matrix_plant,
                                                     ind_vect = "fdis", details_returned = TRUE)

details_list_plant <- alpha_fd_indices_plant$"details"
```

```{r}
# Get functional dispersion
fdis_plant <- alpha_fd_indices_plant$functional_diversity_indices$fdis
```


## Mapping FD

```{r}
# Generate coordinates
subset_coords_plant <-site_loc_key_plant_100km[rowSums(PAM_plant_site_final_100km) >= 4, ]
subset_coords_plant_sp <-subset_coords_plant[,1:2 ]

plant_fd_sp <- data.frame(subset_coords_plant_sp, fdis_plant)
```

```{r}
# Convert the dataframe to sf format
spatial_fdis_plant <- st_as_sf(plant_fd_sp, coords = c("Longitude", "Latitude"))
```

```{r}
# set crs of sf objects
spatial_fdis_plant <- spatial_fdis_plant %>% st_set_crs(5389)
```

```{r}
# Extract coordinates 
spatial_fdis_plant_coords <- st_coordinates(spatial_fdis_plant)

# Add coordinates as separate columns
spatial_fdis_plant <- spatial_fdis_plant %>%
  mutate(x = spatial_fdis_plant_coords[, 1], y = spatial_fdis_plant_coords[, 2])
```

```{r}
summary(spatial_fdis_plant)
```

```{r}
TAGrid_100km <- TApoly %>%
  st_make_grid(cellsize = c(100000)) %>%
  st_intersection(TropicalAndes_IUCNHabitat_Forest) %>%
  st_cast("MULTIPOLYGON") %>%
  st_sf() %>%
  mutate(cellid = row_number())

spatial_fdis_plant$cellid <- st_intersects(spatial_fdis_plant, TAGrid_100km)$nn

spatial_fdis_plant_grid <- TAGrid_100km %>%
   st_join(spatial_fdis_plant) %>%
   group_by(cellid) %>%
   summarize(fdis_value = sum(fdis_plant, na.rm = TRUE)) %>%
   ungroup()
```


```{r}
summary(spatial_fdis_plant_grid)
```

```{r}
plantgridFDisTA_100km <-
    ggplot() +
    geom_sf(data = Americas, fill = "white")+
    geom_sf(data = TApoly, fill = "lightgrey", size = 0.1) +
    geom_sf(data = spatial_fdis_plant_grid, aes(fill = fdis_value), color = NA) +
    labs(fill = "FDis") +
    ggtitle("100 km") +
    scale_fill_distiller(palette = "Greens", direction = 1) +
    coord_sf(xlim = c(-82, -60), ylim = c(-24, 14), expand = FALSE, crs = 4326) +
    theme(panel.background = element_rect(fill = "lightblue"),
        text = element_text(size = 12), plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1))
plantgridFDisTA_100km
```

```{r}
# Extract cell values
plant_cellFDis_100km <- spatial_fdis_plant_grid
hist(plant_cellFDis_100km$fdis_value)
```

## 75 km

```{r}
#Need to remove parts of the PAM that have values less than or equal to the number of dimensions (4)
# Calculate row sums
row_sums_plant <- rowSums(PAM_plant_site_final_75km)
subset_matrix_plant <- PAM_plant_site_final_75km[row_sums_plant >= 4, ]
```

```{r}
# match plant names
sp_faxes_coord_plant_sub <- sp_faxes_coord_plant[ , c("PC1", "PC2", "PC3", "PC4")]
summary(sp_faxes_coord_plant_sub)
```

```{r}
## check number of species names
nrow(sp_faxes_coord_plant_sub)
ncol(subset_matrix_plant) 
```

```{r}
sp_faxes_coord_plant_sub_names <- row.names(sp_faxes_coord_plant_sub)
subset_matrix_plant_names <- colnames(subset_matrix_plant)
```

```{r}
sp_faxes_coord_plant_sub <- as.data.frame(sp_faxes_coord_plant_sub)
row.names(sp_faxes_coord_plant_sub) <- sp_faxes_coord_plant_sub_names

sp_faxes_coord_plant_sub_names <- row.names(sp_faxes_coord_plant_sub)
subset_matrix_plant_names <- colnames(subset_matrix_plant)

plant_names <- intersect(sp_faxes_coord_plant_sub_names, subset_matrix_plant_names)
plant_names <- na.omit(plant_names)

sp_faxes_coord_plant_sub <- sp_faxes_coord_plant_sub[ which((row.names(sp_faxes_coord_plant_sub) %in% plant_names)==TRUE), ]

subset_matrix_plant  <- as.data.frame(subset_matrix_plant)
subset_matrix_plant <- subset_matrix_plant[ ,which((colnames(subset_matrix_plant) %in% plant_names)==TRUE)]

#remove NAs
sp_faxes_coord_plant_sub <- na.omit(sp_faxes_coord_plant_sub)
subset_matrix_plant <- na.omit(subset_matrix_plant)
```

```{r}
nrow(sp_faxes_coord_plant_sub)
ncol(subset_matrix_plant)
```

```{r}
sp_faxes_coord_plant_sub <- as.matrix(sp_faxes_coord_plant_sub)
subset_matrix_plant <- as.matrix(subset_matrix_plant)
```

```{r}
# Computing FD
# The number of species per assemblage has to be higher or equal to the number of traits

alpha_fd_indices_plant <- mFD::alpha.fd.multidim(sp_faxes_coord = sp_faxes_coord_plant_sub, asb_sp_w = subset_matrix_plant,
                                                     ind_vect = "fdis", details_returned = TRUE)

details_list_plant <- alpha_fd_indices_plant$"details"
```

```{r}
# Get functional dispersion
fdis_plant <- alpha_fd_indices_plant$functional_diversity_indices$fdis
```


## Mapping FD

```{r}
# Generate coordinates
subset_coords_plant <-site_loc_key_plant_75km[rowSums(PAM_plant_site_final_75km) >= 4, ]
subset_coords_plant_sp <-subset_coords_plant[,1:2 ]

plant_fd_sp_75km <- data.frame(subset_coords_plant_sp, fdis_plant)
```

```{r}
# Convert the dataframe to sf format
spatial_fdis_plant_75km <- st_as_sf(plant_fd_sp_75km, coords = c("Longitude", "Latitude"))
```

```{r}
# set crs of sf objects
spatial_fdis_plant_75km <- spatial_fdis_plant_75km %>% st_set_crs(5389)
```

```{r}
# Extract coordinates 
spatial_fdis_plant_coords_75km <- st_coordinates(spatial_fdis_plant_75km)

# Add coordinates as separate columns
spatial_fdis_plant_75km <- spatial_fdis_plant_75km %>%
  mutate(x = spatial_fdis_plant_coords_75km[, 1], y = spatial_fdis_plant_coords_75km[, 2])
```

```{r}
summary(spatial_fdis_plant_75km)
```

```{r}
TAGrid__75km <- TApoly %>%
  st_make_grid(cellsize = c(75000)) %>%
  st_intersection(TropicalAndes_IUCNHabitat_Forest) %>%
  st_cast("MULTIPOLYGON") %>%
  st_sf() %>%
  mutate(cellid = row_number())

spatial_fdis_plant_75km$cellid <- st_intersects(spatial_fdis_plant_75km, TAGrid_75km)$nn

spatial_fdis_plant_grid_75km <- TAGrid_75km %>%
   st_join(spatial_fdis_plant_75km) %>%
   group_by(cellid) %>%
   summarize(fdis_value = sum(fdis_plant, na.rm = TRUE)) %>%
   ungroup()
```

```{r}
summary(spatial_fdis_plant_grid_75km)
```

```{r}
plantgridFDisTA_75km <-
    ggplot() +
    geom_sf(data = Americas, fill = "white")+
    geom_sf(data = TApoly, fill = "lightgrey", size = 0.1) +
    geom_sf(data = spatial_fdis_plant_grid_75km, aes(fill = fdis_value), color = NA) +
    labs(fill = "FDis") +
    ggtitle("100 km") +
    scale_fill_distiller(palette = "Greens", direction = 1) +
    coord_sf(xlim = c(-82, -60), ylim = c(-24, 14), expand = FALSE, crs = 4326) +
    theme(panel.background = element_rect(fill = "lightblue"),
        text = element_text(size = 12), plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1))
plantgridFDisTA_75km
```