---
title: "Tropical Andes Taxonomic Diversity of Plants and Frugivores"
author: "Hazel J. Anderson"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "Calculating and mapping taxonomic diversity as species richness using occurrence data for plants and frugivores in the Tropical Andes Moist Lowland and Montane forests. Note: some code is adapted from https://luisdva.github.io/rstats/richness/."
data input: "TropicalAndes_plant_occ.csv, TropicalAndes_frugivore_occ.csv"
data output: "TropicalAndes_frugivore_richness.csv, TropicalAndes_GBIF_plant_richness.csv"
date: "2023-08-01"
output: html_document
---

# Load required packages
```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(rnaturalearth)
library(smoothr)
library(purrr)
library(raster)
library(scico)
library(ggspatial)
```

# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1')
data_path2<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L2')
```

# Read in Data
```{r}
TropicalAndes_plant_occ_forest <- read.csv(file.path(data_path,"TropicalAndes_plant_occ_forest.csv"))
TropicalAndes_frugivore_occ_forest <- read.csv(file.path(data_path,"TropicalAndes_frugivore_occ_forest.csv"))
TropicalAndes_IUCNHabitat_Forest <- raster(file.path(data_path2, "TropicalAndes_IUCNHabitat_Forest.tif"))
```

# Polygons of countries
```{r}
worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")
#polygon of Tropical Andes
TApoly <- worldMap %>% filter(sovereignt == "Bolivia" |sovereignt == "Ecuador" | sovereignt == "Venezuela" | sovereignt == "Colombia" | sovereignt == "Peru")
```

# Convert data to spatial data
```{r}
plants.sf <- st_as_sf(TropicalAndes_plant_occ_forest, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)

frugivores.sf <- st_as_sf(TropicalAndes_frugivore_occ_forest, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
```

```{r}
plants_sf_species <- plants.sf %>%
  group_by(species) %>%
  summarise()

frugivores_sf_species <- frugivores.sf %>%
  group_by(species) %>%
  summarise()
```

# Plot Base Map
```{r}
basePlot <-
ggplot() +
geom_sf(data = worldMap, fill = "white") +
geom_sf(data = TApoly) +
labs(title = "Tropical Andes", x = "Latitude", y = "Longitude") +
coord_sf(xlim = c(-85, -54), ylim = c(-24, 14), expand = FALSE) +
annotation_scale(location = "bl", width_hint = 0.5) +
annotation_north_arrow(location = "bl", which_north = "true", 
  pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), style = north_arrow_fancy_orienteering) +
theme(panel.background = element_rect(fill = "lightblue"))

basePlot
```

# Plot points
```{r}
plantsPointsPlot <-
  ggplot() +
  geom_sf(data = worldMap, fill = "white") +
  geom_sf(data = TApoly) +
  geom_sf(data = plants_sf_species, pch = 21) +
  labs(title = "Tropical Andes Plant Occurrences", x = "Latitude", y = "Longitude") +
  coord_sf(xlim = c(-85, -54), ylim = c(-24, 14), expand = FALSE) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "lightblue"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
plantsPointsPlot
```

```{r}
frugivoresPointsPlot <-
  ggplot() +
  geom_sf(data = worldMap, fill = "white") +
  geom_sf(data = TApoly) +
  geom_sf(data = frugivores_sf_species, pch = 21) +
  labs(title = "Tropical Andes Frugivore Occurrences", x = "Latitude", y = "Longitude") +
  coord_sf(xlim = c(-85, -54), ylim = c(-24, 14), expand = FALSE) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "lightblue"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
frugivoresPointsPlot
```

# Mask grid by forest
```{r}
TropicalAndes_IUCNHabitat_Forest <- aggregate(TropicalAndes_IUCNHabitat_Forest, 50, fun=mean, na.rm=TRUE)
TropicalAndes_IUCNHabitat_Forest
```

```{r}
Forest_poly <- rasterToPolygons(TropicalAndes_IUCNHabitat_Forest, na.rm = TRUE, dissolve = TRUE)
Forest_poly
plot(Forest_poly)
```

```{r}
Forest_sf <- st_as_sf(Forest_poly)
Forest_sf
plot(Forest_sf)
```

# Make 0.75 Grid
```{r}
# make grid
TAGrid0.75 <- TApoly %>%
  st_make_grid(cellsize = c(0.75)) %>%
  st_intersection(Forest_sf) %>%
  st_cast("MULTIPOLYGON") %>%
  st_sf() %>%
  mutate(cellid = row_number())
```

# Plot Empty Grid
```{r}
# empty grid
gridPlot <-
  ggplot() +
  geom_sf(data = worldMap, fill = "white")+
  geom_sf(data = Forest_sf) +
  geom_sf(data = TAGrid0.75) +
  labs(title = "Tropical Andes Grid [0.75°]", x = "Latitude", y = "Longitude") +
  coord_sf(xlim = c(-85, -54), ylim = c(-24, 14), expand = FALSE) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "lightblue"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
gridPlot
```

# Cell Richness
```{r}
plant_richness_grid0.75 <- TAGrid0.75 %>%
  st_join(plants_sf_species) %>%
  mutate(overlap = ifelse(!is.na(species), 1, 0)) %>%
  group_by(cellid) %>%
  summarize(num_species = sum(overlap))
```

```{r}
frugivore_richness_grid0.75 <- TAGrid0.75 %>%
  st_join(frugivores_sf_species) %>%
  mutate(overlap = ifelse(!is.na(species), 1, 0)) %>%
  group_by(cellid) %>%
  summarize(num_species = sum(overlap))
```

# Richness plots
```{r}
plantgridRichTA0.75 <-
  ggplot(plant_richness_grid0.75) +
  geom_sf(data = worldMap, fill = "white")+
  geom_sf(data = TApoly, fill = "grey", size = 0.1) +
  geom_sf(aes(fill = num_species), color = NA) +
  scale_fill_scico(palette = "romaO", direction = 1, end = 0.9, midpoint = 1500) +
  coord_sf(xlim = c(-85, -54), ylim = c(-24, 14), expand = FALSE) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "lightblue"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  ) +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true", 
  pad_x = unit(0.3, "in"), pad_y = unit(0.3, "in"), style = north_arrow_fancy_orienteering) +
  labs(title = "Tropical Andes Plant Raw Richness", x = "Longitude", y = "Latitude", fill = "Number of species")
plantgridRichTA0.75
```

```{r}
frugivoregridRichTA0.75 <-
  ggplot(frugivore_richness_grid0.75) +
  geom_sf(data = worldMap, fill = "white")+
  geom_sf(data = TApoly, fill = "grey", size = 0.1) +
  geom_sf(aes(fill = num_species), color = NA) +
  scale_fill_scico(palette = "romaO", direction = 1, end = 0.9, midpoint = 225) +
  coord_sf(xlim = c(-85, -54), ylim = c(-24, 14), expand = FALSE) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "lightblue"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  ) +   
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true", 
  pad_x = unit(0.3, "in"), pad_y = unit(0.3, "in"), style = north_arrow_fancy_orienteering) +
  labs(title = "Tropical Andes Frugivore Raw Richness", x = "Longitude", y = "Latitude", fill = "Number of species")
frugivoregridRichTA0.75
```


# Extract cell values
```{r}
plant_cellRichness0.75 <- plantgridRichTA0.75[["data"]]
frugivore_cellRichness0.75 <- frugivoregridRichTA0.75[["data"]]
```


```{r}
plot(plant_cellRichness0.75$num_species, frugivore_cellRichness0.75$num_species,
     main = "Plant Richness vs Frugivore Richness",
     xlab = "Plant Richness by cell", ylab = "Frugivore Richness by cell")
abline(lm(frugivore_cellRichness0.75$num_species ~ plant_cellRichness0.75$num_species))
summary(lm(frugivore_cellRichness0.75$num_species ~ plant_cellRichness0.75$num_species))
```

```{r}
hist(plant_cellRichness0.75$num_species,
     main = "Histogram of Plant Richness by cell",
     xlab = "Plant Richness by cell")
hist(frugivore_cellRichness0.75$num_species,
     main = "Histogram of Frugivore Richness by cell",
     xlab = "Frugivore Richness by cell")
```

```{r}
summary(plant_cellRichness0.75$num_species)
summary(frugivore_cellRichness0.75$num_species)
```

# Write data to csv
```{r}
write.csv(plant_cellRichness0.75, file.path(output_path,"TropicalAndes_GBIF_plant_richness.csv"))
write.csv(frugivore_cellRichness0.75, file.path(output_path,"TropicalAndes_frugivore_richness.csv"))
```
