---
title: "Ecuador plant species list"
authors: "Hazel Anderson"
collaborators: "None"
data input: "PlantsOfTheWorldOnline_Ecuador_species.xlsx and GBIF_Ecuador_PlantSpeciesList.csv"
data output: "Ecuador_unique_species_list.csv"
project: "Frugivoria"
date: "2022-08-17"
output: html_document
---
# Set Working directory
```{r}
setwd('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(BIEN)
library(tidyr)
```


# Pull Ecuador plant species lists from various sources

## BIEN
```{r}
Ecuador_BIEN <- BIEN_occurrence_country("Ecuador")
write.csv(Ecuador_BIEN, "Ecuador_BIEN_species_list.csv")
```


## Kew Plants of the World Online
```{r}
library(readxl)
Ecuador_POWO <- read_excel("G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0/PlantsOfTheWorldOnline_Ecuador_species.xlsx")
#won't read in csv version for some reason
```

## GBIF
```{r}
Ecuador_GBIF <- read.csv("G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0/GBIF_Ecuador_PlantSpeciesList.csv")
```

# Combine data
```{r}
species_GBIF <- as.list(Ecuador_GBIF$species)
species_BIEN <- as.list(Ecuador_BIEN$scrubbed_species_binomial)
species_POWO <- as.list(Ecuador_POWO$genus)
genus_POWO <- as.list(Ecuador_POWO$species)

#need to combine species_POWO and genus_POWO
species_POWO <- as.list(paste(genus_POWO, species_POWO, sep=" "))

#combine all 3 species list together
all_species <- c(species_BIEN, species_GBIF, species_POWO)

#remove duplicates
unique_species <- unique(all_species)

```

# Output data to csv
```{r}
write.csv(unique_species, "Ecuador_unique_species_list.csv")
```

