---
title: "Ecudor plant species IUCN statuses"
author: "Hazel Anderson"
collaborators: "None"
data input: "Ecuador_unique_species_list.csv"
data output: "TBD"
project: "Frugivoria"
date: "2022-08-31"
output: html_document
---
# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Install and load required packages
```{r}
for (package in c("httr", "jsonlite", "rredlist", "dplyr")) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}
```

```{r}
## Token for accessing IUCN data through their API
## User must obtain a token (https://apiv3.iucnredlist.org/api/v3/token) before using the 'rredlist package'.
token <- 'f632af67ee5eef8446a8cb0ca394e1f1cb369ca5eab626edc4ea46e5698deb25'
api_url <- 'https://apiv3.iucnredlist.org/api/v3/'

#Ecuador
ecuador_species <- rl_sp_country("EC", key = token, parse = TRUE)
ecuador_species <- ecuador_species$result[1]

# Get codes for the different species groups
grp_codes <- GET(url = paste0(api_url, 'comp-group/list?token=', token))
code <-fromJSON(content(grp_codes, as = 'text'), simplifyDataFrame = TRUE, flatten = TRUE)$result
```

```{r}
# Get species list of all plants across all countries
mangrove_plants <- rl_comp_groups(group = 'mangrove_plants', key = token)
p1 <- mangrove_plants$result[1]
seagrasses<- rl_comp_groups(group = 'seagrasses', key = token)
p2 <- seagrasses$result[1]
cycads <- rl_comp_groups(group = 'cycads', key = token)
p3 <- cycads$result[1]
magnolias <- rl_comp_groups(group = 'magnolias', key = token)
p4 <- magnolias$result[1]
confiers <- rl_comp_groups(group = 'conifers', key = token)
p5 <- confiers$result[1]
cacti <- rl_comp_groups(group = 'cacti', key = token)
p6 <- cacti$result[1]

all_plants <- rbind(p1, p2, p3, p4, p5, p6)
```

```{r}
ecuador_plants <- merge(all_plants, ecuador_species, by="taxonid")
ecuador_plants_unique <- distinct(ecuador_plants, scientific_name, .keep_all = TRUE)
```

