---
title: "Ecuador plant species TRY data"
author: "Hazel J. Anderson"
collaborators: "None"
data input: "None"
data output: "Ecuador_TRY_plant_traits.csv"
project: "Frugivoria"
date: "2022-10-27"
output: html_document
---


# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(rtry)
library(mde)
library(DataExplorer)
library(summarytools)
```

# Read in TRY data
Data was obtained from https://www.try-db.org/TryWeb/Prop0.php 
```{r}
data <- rtry_import("G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0/TRY/TRY_Ecuador_PublicData_10192020.txt")
```
# Explore TRY data
```{r}
# explore by trait id and trait name
TRYdata_explore_trait <- rtry_explore(data, TraitID, TraitName)
TRYdata_explore_trait

# explore by species id, species name, trait id, and trait name
TRYdata_explore_species <- rtry_explore(data, AccSpeciesID, AccSpeciesName, TraitID, TraitName)
TRYdata_explore_species

# explore by data id, data name, trait id, and trait name sorted by trait id
TRYdata_explore_anc <- rtry_explore(data, DataID, DataName, TraitID, TraitName, sortBy = TraitID)
TRYdata_explore_anc
```

# Summary of data
```{r}
summary(data)
na_summary(data, , exclude_cols = c("RelUncertaintyPercent", "V28"))
```

### using DataExplorer package
```{r}
plot_str(data)
introduce(data)
plot_intro(data)
plot_missing(data)
plot_bar(data)
```

### using summarytools package
```{r}
ecuador_TRY_plant_traits_summary <- dfSummary(data, 
            na.col       = FALSE,
            style        = "multiline",
            plain.ascii  = TRUE,
            graph.magnif = .8)
print(ecuador_TRY_plant_traits_summary, method = "render")
view(ecuador_TRY_plant_traits_summary, file = file.path(output_path,"Ecuador_TRY_summary.html"))
# gives the following error: Error in withCallingHandlers(expr, warning = function(w) if (inherits(w, : 
#   invalid multibyte string at '<b0>45''
```

# Write data to csv
```{r}
ecuador_TRY_plant_traits_path <- file.path(output_path,"Ecuador_TRY_plant_traits.csv")
write.csv(data, file = ecuador_TRY_plant_traits_path)

```