---
title: "Ecuador Elevation"
author: "Hazel J. Anderson"
collaborators: "None"
data input: "None"
data output: "ecuador_geodata_elevation.RData and ecuador_elevatr_elevation.RData"
project: "Frugivoria"
date: "2022-10-21"
output: html_document
---


# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(geodata)
library(elevatr)
```


# Download elevation data for Ecuador using geodata
```{r}
# get outline of Ecuador
ecuador_outline <- gadm(country = "ECU", level=0, path = data_path, version="latest", resolution=1)
ecuador_outline

# get elevation data for Ecuador
ecuador_geodata <- elevation_30s(country = "ECU", path = data_path)
ecuador_geodata

# look at elevation data
plot(ecuador_geodata)
plot(ecuador_outline, add = T)

#save elevation data to file
ecuador_geodata_elevation_path <- file.path(output_path,"ecuador_geodata_elevation.RData") 
save(ecuador_geodata, file = ecuador_geodata_elevation_path)
```

# Download elevation data for Ecuador using 'elevatr'
```{r}
# convert ecuador_outline to spatial dataframe
ecuador_outline.df <- sf::st_as_sf(ecuador_outline)

# get elevation data for Ecuador
ecuador_elevatr <- get_elev_raster(ecuador_outline.df, z= 5)

# plot elevation
plot(ecuador_elevatr)
plot(ecuador_outline, add = T)

#save elevation data to file
ecuador_elevatr_elevation_path <- file.path(output_path,"ecuador_elevatr_elevation.RData") 
save(ecuador_elevatr, file = ecuador_elevatr_elevation_path)
```