---
title: "Northern Andes plant species IUCN data"
author: "Hazel J. Anderson"
collaborators: "None"
data input: "None"
data output: "NorthAndes_IUCN_plant_species.csv, NorthAndes_IUCN_plant_occ.csv, NorthAndes_IUCN_plant_habitat.csv"
project: "Frugivoria"
date: "2023-02-27"
output: html_document
---
# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Install and load required packages
```{r}
library(httr)
library(jsonlite)
library(rredlist)
library(dplyr)
library(mde)
library(DataExplorer)
library(summarytools)
```

# Set up token and api url
```{r}
## Token for accessing IUCN data through their API
## User must obtain a token (https://apiv3.iucnredlist.org/api/v3/token) before using the 'rredlist package'.
token <- 'f632af67ee5eef8446a8cb0ca394e1f1cb369ca5eab626edc4ea46e5698deb25'
api_url <- 'https://apiv3.iucnredlist.org/api/v3/'

```

# North Andes species list
```{r}
#Ecuador
ecuador_species <- rl_sp_country("EC", key = token, parse = TRUE)
ecuador_species <- ecuador_species$result[1]
#Colombia
colombia_species <- rl_sp_country("CO", key = token, parse = TRUE)
colombia_species <- colombia_species$result[1]
#Venezuela
venezuela_species <- rl_sp_country("VE", key = token, parse = TRUE)
venezuela_species <- venezuela_species$result[1]

#combine all 3
northAndes_species <- rbind(ecuador_species, colombia_species, venezuela_species)
```

# Plant species list
```{r}
# Get codes for the different species groups
grp_codes <- GET(url = paste0(api_url, 'comp-group/list?token=', token))
code <-fromJSON(content(grp_codes, as = 'text'), simplifyDataFrame = TRUE, flatten = TRUE)$result
```

```{r}
# Get species list of all plants across all countries
mangrove_plants <- rl_comp_groups(group = 'mangrove_plants', key = token)
p1 <- as.data.frame(mangrove_plants$result)
seagrasses<- rl_comp_groups(group = 'seagrasses', key = token)
p2 <- as.data.frame(seagrasses$result)
cycads <- rl_comp_groups(group = 'cycads', key = token)
p3 <- as.data.frame(cycads$result)
magnolias <- rl_comp_groups(group = 'magnolias', key = token)
p4 <- as.data.frame(magnolias$result)
confiers <- rl_comp_groups(group = 'conifers', key = token)
p5 <- as.data.frame(confiers$result)
cacti <- rl_comp_groups(group = 'cacti', key = token)
p6 <- as.data.frame(cacti$result)

all_plants <- rbind(p1, p2, p3, p4, p5, p6)
```

# Generate Northern Andes plant species list
```{r}
northAndes_plants <- merge(all_plants, northAndes_species, by="taxonid")
```

# Get occurences for Northern Andes using species list
```{r}
get_occ <- function(ID) {
  rl_occ_country<- rl_occ_country(id=ID,key=token)$result
  if (class(rl_occ_country) == 'data.frame') {
    data.frame(taxonid=ID, rl_occ_country)
  } else {
    data.frame(taxonid=ID)
  }
}
northAndes_IUCN_plant_occ <- northAndes_plants %>%
  rowwise %>%
  do(get_occ(.$taxonid))
northAndes_IUCN_plant_occ <- as.data.frame(northAndes_IUCN_plant_occ)
```

# Get habitat for species list
```{r}
get_habitat <- function(ID) {
  habitat_by_sp<- rl_habitats(id=ID,key=token)$result
  if (class(habitat_by_sp) == 'data.frame') {
    data.frame(taxonid=ID, habitat_by_sp)
  } else {
    data.frame(taxonid=ID)
  }
}
northAndes_IUCN_plant_habitat <- northAndes_plants %>%
  rowwise %>%
  do(get_habitat(.$taxonid))
northAndes_IUCN_plant_habitat <- as.data.frame(northAndes_IUCN_plant_habitat)
```


# Summary of data
```{r}
summary(northAndes_plants)
na_summary(northAndes_plants, exclude_cols = c("subpopulation"))
```

```{r}
summary(northAndes_IUCN_plant_occ)
na_summary(northAndes_IUCN_plant_occ)
```

```{r}
summary(northAndes_IUCN_plant_habitat)
na_summary(northAndes_IUCN_plant_habitat)
```

### using DataExplorer package
```{r}
plot_str(northAndes_plants)
introduce(northAndes_plants)
plot_intro(northAndes_plants)
plot_missing(northAndes_plants)
plot_bar(northAndes_plants)
```

```{r}
plot_str(northAndes_IUCN_plant_occ)
introduce(northAndes_IUCN_plant_occ)
plot_intro(northAndes_IUCN_plant_occ)
plot_missing(northAndes_IUCN_plant_occ)
plot_bar(northAndes_IUCN_plant_occ)
```

```{r}
plot_str(northAndes_IUCN_plant_habitat)
introduce(northAndes_IUCN_plant_habitat)
plot_intro(northAndes_IUCN_plant_habitat)
plot_missing(northAndes_IUCN_plant_habitat)
plot_bar(northAndes_IUCN_plant_habitat)
```

### using summarytools package
```{r}
northAndes_plants_summary <- dfSummary(northAndes_plants, 
            na.col       = FALSE,
            style        = "multiline",
            plain.ascii  = TRUE,
            graph.magnif = .8)
print(northAndes_plants_summary, method = "render")
view(northAndes_plants_summary, file = file.path(output_path,"northAndes_plants_summary.html"))
```

```{r}
northAndes_IUCN_plant_occ_summary <- dfSummary(northAndes_IUCN_plant_occ, 
            na.col       = FALSE,
            style        = "multiline",
            plain.ascii  = TRUE,
            graph.magnif = .8)
print(northAndes_IUCN_plant_occ_summary, method = "render")
view(northAndes_IUCN_plant_occ_summary, file = file.path(output_path,"northAndes_IUCN_plant_occ_summary.html"))
```

```{r}
northAndes_IUCN_plant_habitat_summary <- dfSummary(northAndes_IUCN_plant_habitat, 
            na.col       = FALSE,
            style        = "multiline",
            plain.ascii  = TRUE,
            graph.magnif = .8)
print(northAndes_IUCN_plant_habitat_summary, method = "render")
view(northAndes_IUCN_plant_habitat_summary, file = file.path(output_path,"northAndes_IUCN_plant_habitat_summary.html"))
```

# Write data to csv
```{r}
northAndes_ICUN_species_list_path <- file.path(output_path,"northAndes_IUCN_plant_species.csv")
write.csv(northAndes_plants, file = northAndes_ICUN_species_list_path)

northAndes_IUCN_plant_occ_path <- file.path(output_path, "northAndes_IUCN_plant_occ.csv")
write.csv(northAndes_IUCN_plant_occ, file = northAndes_IUCN_plant_occ_path)

northAndes_IUCN_plant_habitat_path <- file.path(output_path, "northAndes_IUCN_plant_habitat.csv")
write.csv(northAndes_IUCN_plant_habitat, file = northAndes_IUCN_plant_habitat_path)
```



