---
title: "Tropical Andes plant occurrence data GBIF"
author: "Hazel J. Anderson"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "This script retrives plant occurrence data from GBIF using a subset of species with IUCN habitat designations ‘Forest-Subtropical/Tropical Moist Montane’ and/or ‘Forest-Subtropical/Tropical Moist Lowland’. Data is also retrived without the subset for species in the countries that make up the Tropical Andes to be spatially subset later, as not many plant species are assessed on the IUCN RedList. "
data input: "IUCN/Tropical Andes Plants - Search Results/habitats.csv"
data output: "TropAndes_GBIF_plant_occ.csv"
date: "2023-07-18"
output: html_document
---

# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(dplyr)
library(rgbif)
library(raster)
library(sf)
```

# Download plant occurrence data from GBIF
```{r}
occ_download(
pred("taxonKey", 6),
pred("hasCoordinate", TRUE),
pred("hasGeospatialIssue", FALSE),
pred_in("country",c("EC","CO","VE", "PE", "BO")),
format = "SIMPLE_CSV"
)
```

## Retrive GBIF download, save file, and load into r
```{r}
d1 <- occ_download_get("0001452-230918134249559", path = output_path, overwrite = TRUE) %>%
  occ_download_import()
```

# Summary 
```{r}
glimpse(d1)
```

```{r}
print("The number of occurrences is")
nrow(d1)
print("The number of species is" )
length(unique(d1$species))
print("The number of genera is" )
length(unique(d1$genus))
print("The number of families is" )
length(unique(d1$family))
```

# Extract species list
```{r}
GBIF_SpeciesList <- unique(d1$species)
```


# Write data to csv
```{r}
TropicalAndes_GBIF_path <- file.path(output_path,"TropicalAndes_GBIF_plant_occ.csv") 
write.csv(d1, file = TropicalAndes_GBIF_path)
TropicalAndes_GBIF_species_path <- file.path(output_path,"TropicalAndes_GBIF_plant_species.csv") 
write.csv(GBIF_SpeciesList, file = TropicalAndes_GBIF_species_path)
```
