---
title: "Tropical Andes montane and lowland forest bird and mammal species GBIF"
author: "Hazel J. Anderson"
collaborators: "None"
data input: "None"
data output: "TropAndes_GBIF_frugivore_occ.csv"
project: "Frugivoria"
date: "2023-04-06"
output: html_document
---

# Set file paths
```{r}
data_path<-file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path<- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(dplyr)
library(rgbif) 
```

# Read in IUCN data
Data was obtained from https://www.iucnredlist.org/search?permalink=f4407d96-c039-413a-8d46-707f262271ee
```{r}
frugivore_habitats <- read.csv(file.path(data_path,"IUCN/Tropical Andes Birds and Mammals - Search Results/habitats.csv"))
```

# Create species list from IUCN data
```{r}
frugivore_species <- unique(frugivore_habitats$scientificName)
write.csv2(frugivore_species, file = file.path(output_path, "TropicalFrugivoreSpecies.csv"))
```

# Match species names to GBIF
```{r}
gbif_taxon_keys <- frugivore_species %>% 
name_backbone_checklist() %>% # match to backbone 
filter(!matchType == "NONE") %>% # get matched names
pull(usageKey) 
```

# Download data
```{r}
occ_download(
pred_in("taxonKey", gbif_taxon_keys),
pred("hasCoordinate", TRUE),
pred("hasGeospatialIssue", FALSE),
pred_in("country",c("EC","CO","VE", "PE", "BO")), 
format = "SIMPLE_CSV"
)
```

# Retrive GBIF download, save file, and load into r
```{r}
d <- occ_download_get("0154158-230224095556074", path = output_path) %>%
  occ_download_import()
```

# Summary 
```{r}
glimpse(d)
```

```{r}
print("The number of records is")
nrow(d)
print("The number of species is")
length(unique(d$species))
print("The number of families is")
length(unique(d$family))
```

# Extract species list
```{r}
GBIF_occ_SpeciesList <- unique(d$species)
```

# Write data to csv
```{r}
TropicalAndes_GBIF_path <- file.path(output_path,"TropAndes_GBIF_frugivore_occ.csv") 
write.csv(d, file = TropicalAndes_GBIF_path)
TropicalAndes_GBIF_species_path <- file.path(output_path,"TropAndes_GBIF_frugivore_occ_species.csv") 
write.csv(GBIF_occ_SpeciesList, file = TropicalAndes_GBIF_path)
```