---
title: "Tropical Andes IUCN Montane and Lowland forest"
author: "Hazel J. Anderson"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "Create raster of IUCN habitat classification Forest-Subtropical moist montane and Forest - Subtropical moist lowland for Tropical Andes."
data input: "iucn_habitatclassification_composite_lvl2_ver004.tif"
data output: "TropicalAndes_IUCNHabitat_Forest.GTiff"
date: "2023-07-18"
output: html_document
---


# Set file paths
```{r}
data_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(raster)
library(sf)
library(rnaturalearth)
library(dplyr)
library(terra)
```

# Load in Ecosystem Functional Groups
Data downloaded from https://zenodo.org/record/4058819
Citation: Martin Jung, Prabhat Raj Dahal, Stuart H. M. Butchart, Paul F. Donald, Xavier De Lamo, Myroslava Lesiv, … Piero Visconti. (2020). A global map of terrestrial habitat types (Version 004) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.4058819

```{r}
iucn_moist_montane_forest <- raster(file.path(data_path, "iucn_habitatclassification_composite_lvl2_ver004/lvl2_frac_1km_ver004/iucn_habitatclassification_fraction_lvl2__109_Forest – Subtropical-tropical moist montane__ver004.tif"))
iucn_moist_lowland_forest <- raster(file.path(data_path, "iucn_habitatclassification_composite_lvl2_ver004/lvl2_frac_1km_ver004/iucn_habitatclassification_fraction_lvl2__106_Forest – Subtropical-tropical moist lowland__ver004.tif"))
```

```{r}
plot(iucn_moist_montane_forest)
plot(iucn_moist_lowland_forest)
```

# Crop extent - trim to Andean States
```{r}
# Pull in world map
worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")

# Subset world map to Tropical Andes
study_region <-  worldMap %>% filter(sovereignt == "Bolivia" | sovereignt == "Ecuador" | sovereignt == "Venezuela" | sovereignt == "Colombia" | sovereignt == "Peru")
plot(study_region$geometry)
```

```{r}
# crop moist montane to tropical andes
iucn_moist_montane_forest_crop <- crop(iucn_moist_montane_forest, study_region)
TA_iucn_moist_montane_forest <- mask(iucn_moist_montane_forest_crop, study_region)
plot(TA_iucn_moist_montane_forest)
TA_iucn_moist_montane_forest
```

```{r}
#crop moist lowland to tropical andes
iucn_moist_lowland_forest_crop <- crop(iucn_moist_lowland_forest, study_region)
TA_iucn_moist_lowland_forest <- mask(iucn_moist_lowland_forest_crop, study_region)
plot(TA_iucn_moist_lowland_forest)
TA_iucn_moist_lowland_forest
```


```{r}
# combine TA_iucn_moist_lowland_forest & TA_iucn_moist_montane_forest into one raster
TA_iucn_habitat_forest <- merge(TA_iucn_moist_lowland_forest, TA_iucn_moist_montane_forest)
plot(TA_iucn_habitat_forest)
TA_iucn_habitat_forest
```

# Save raster
```{r}
writeRaster(TA_iucn_habitat_forest, filename = file.path(output_path, "TropicalAndes_IUCNHabitat_Forest.GTiff"), format = "GTiff", overwrite=TRUE)
writeRaster(TA_iucn_moist_montane_forest, filename = file.path(output_path, "TropicalAndes_IUCNHabitat_Forest_Montane.GTiff"), format = "GTiff", overwrite=TRUE)
writeRaster(TA_iucn_moist_lowland_forest, filename = file.path(output_path, "TropicalAndes_IUCNHabitat_Forest_Lowland.GTiff"), format = "GTiff", overwrite=TRUE)
```

# Convert to sf
```{r}
# convert to SpatRaster
TA_iucn_habitat_forest_sr <- as(TA_iucn_habitat_forest, "SpatRaster")
TA_iucn_habitat_forest_sr
```


```{r}
TA_iucn_habitat_forest_sv <- as.polygons(TA_iucn_habitat_forest_sr)
TA_iucn_habitat_forest_sv
plot(TA_iucn_habitat_forest_sv)
```

```{r}
TA_iucn_habitat_forest_shape <- sf::st_as_sf(TA_iucn_habitat_forest_sv)
TA_iucn_habitat_forest_shape
plot(TA_iucn_habitat_forest_shape)
```

# Save shapefile
```{r}
st_write(TA_iucn_habitat_forest_shape, file.path(output_path, "TropicalAndes_IUCNHabitat_Forest.shp"), overwrite=TRUE)
```

