---
title: "Tropical Andes plant trait data TRY"
author: "Hazel J. Anderson"
project: "Plant-Frugivore Diversity"
collaborators: "Beth E. Gerstner, Phoebe L. Zarnetske"
overview: "This script retrieves plant trait data from the TRY database for plant species list."
data input: "none"
data output: "TropicalAndes_TRY_traits.csv"
date: "2023-07-18"
output: html_document
---

# Set file paths
```{r}
data_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
output_path <- file.path('G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0')
```

# Load required packages
```{r}
library(rtry)
library(dplyr)
```


# Load TRY data
Data was obtained from https://www.try-db.org/TryWeb/Prop0.php 
```{r}
try_data <- rtry_import("G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L0/TRY/28165_02082023081407/28165.txt")
```

```{r}
glimpse(try_data)
```

#Subset to species list
```{r}
species_list <- read.csv("G:/Shared drives/SpaCE_Lab_FRUGIVORIA/data/plants/L1/TropicalAndes_plant_Forest_SpeciesList.csv")
species_list <- species_list$x
```

```{r}
try_data_filtered <- try_data %>%
  filter(AccSpeciesName %in% species_list)
```


# Summary 
```{r}
glimpse(try_data_filtered)
```

```{r}
print("The number of records is")
nrow(try_data_filtered)
print("The number of species is" )
length(unique(try_data_filtered$AccSpeciesName))
```


```{r}
try_data_filtered %>% count(TraitName)
```


# Write data to csv
```{r}
TropicalAndes_TRY_path <- file.path(output_path,"TropicalAndes_TRY_plant_traits_forestSpecies.csv") 
write.csv(try_data_filtered, file = TropicalAndes_TRY_path)
```
